### ISSUE TITLE
Problems with drawing

### ISSUE THREAD

**Issue by jtheis1993** [Webstrates/tutorials#5]
Hello, I followed the tutorial, but I can not draw anything.
Running the latest chrome, nodeJS, npm and windows 10

**Comment by kbadk** [comment]
The pad created using the pad tutorial isn't meant to work with a mouse, it's designed to work with [touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events), for instance an Apple Pencil on an iPad or a stylus on a touchscreen.
